= fbcearlville.org Documentation
Michael Phillips <linux478@gmail.org>
:toc:
:icons: font



{url-asciidoc-reference}[Asciidoc Reference,window=_blank]

== Wordpress

=== Plugins

==== Updraftplus

Automatic backups are set to weekly for the website and daily for the database.
Currently keeping 52 copies for website and 30 for database.
The remote backups are going to fbcearlville@gmail.com Google Drive.

== Configuration

=== Email Accounts

* {site-users-bandofbrothers-email-url}[{site-users-bandofbrothers-email}] - ministry for men called Band Of Brothers
* {site-users-board-email-url}[{site-users-board-email}] - the board of the church
* {site-users-events-email-url}[{site-users-events-email}] - contact for the event provided by the church
* {site-users-pastor-email-url}[{site-users-pastor-email}] - contact for the current paster
* {site-users-sistersoffaith-email-url}[{site-users-sistersoffaith-email}] - ministry for women called Sisters in Faith
* {site-users-webmaster-email-url}[{site-users-webmaster-email}] - contact for the development of the website

[glossary]
=== Name - Value

[glossary]
Event Ticket Host:: {site-ticketmaster-url}[{site-ticketmaster-name},window=_blank]
Domain Register:: {site-domainname-provider-url}[{site-domainname-provider-name},window=_blank]
Email Provider:: {site-email-provider-url}[{site-email-provider-name},window=_blank]
Hosting Provider:: {site-hosting-provider-url}[{site-hosting-provider-name},window=_blank]
Site Panel:: {site-panal-url}[{site-panal-name},window=_blank]
Site URL:: {site-url}[{site-url}]

== Guides

=== User Roles and Permissions

1. {url-wordpress-administrator}[Administrator,window=_blank]
1. {url-wordpress-editor}[Editor,window=_blank]
1. {url-wordpress-author}[Author,window=_blank]
1. {url-wordpress-contributor}[Contributor,window=_blank]
1. {url-wordpress-subscriber}[Subscriber,window=_blank]
